<?xml version="1.0" encoding="utf-8"?><Database Name="Hotel_Manager" Class="HotelManagerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Hotel_Manager;Persist Security Info=True;User ID=sa" SettingsObjectName="GUI.Properties.Settings" SettingsPropertyName="Hotel_ManagerConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PHONG" Member="PHONGs">
    <Type Name="PHONG">
      <Column Name="MAPHONG" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TRANGTHAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SUCCHUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MALOAIPHONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PHONG_HOADONPH" Member="HOADONPHs" ThisKey="MAPHONG" OtherKey="MAPH" Type="HOADONPH" />
      <Association Name="PHONG_CHITIETHD" Member="CHITIETHDs" ThisKey="MAPHONG" OtherKey="MAPH" Type="CHITIETHD" />
      <Association Name="LOAIPHONG_PHONG" Member="LOAIPHONG" ThisKey="MALOAIPHONG" OtherKey="MALOAIPHONG" Type="LOAIPHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DICHVU" Member="DICHVUs">
    <Type Name="DICHVU">
      <Column Name="MADV" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DICHVU_HOADONPH" Member="HOADONPHs" ThisKey="MADV" OtherKey="MADV" Type="HOADONPH" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIPHONG" Member="LOAIPHONGs">
    <Type Name="LOAIPHONG">
      <Column Name="MALOAIPHONG" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAIPHONG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYCAPNHAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOICAPNHAT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="LOAIPHONG_PHONG" Member="PHONGs" ThisKey="MALOAIPHONG" OtherKey="MALOAIPHONG" Type="PHONG" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="HOTENNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="Char(11)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="QUYEN" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="Char(14)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="DTHOAI" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DCHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="KHACHHANG_HOADONPH" Member="HOADONPHs" ThisKey="MAKH" OtherKey="MAKH" Type="HOADONPH" />
    </Type>
  </Table>
  <Table Name="dbo.HOADONPH" Member="HOADONPHs">
    <Type Name="HOADONPH">
      <Column Name="MAHD" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MADV" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="SOLUONGDV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIADV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MAPH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DONGIAP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYVAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYRA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="HOADONPH_CHITIETHD" Member="CHITIETHD" ThisKey="MAHD" OtherKey="MAHD" Type="CHITIETHD" Cardinality="One" />
      <Association Name="DICHVU_HOADONPH" Member="DICHVU" ThisKey="MADV" OtherKey="MADV" Type="DICHVU" IsForeignKey="true" />
      <Association Name="KHACHHANG_HOADONPH" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="PHONG_HOADONPH" Member="PHONG" ThisKey="MAPH" OtherKey="MAPHONG" Type="PHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETHD" Member="CHITIETHDs">
    <Type Name="CHITIETHD">
      <Column Name="MAHD" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAPH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="TENKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TONGTIENDV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TONGTIENPHONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADONPH_CHITIETHD" Member="HOADONPH" ThisKey="MAHD" OtherKey="MAHD" Type="HOADONPH" IsForeignKey="true" />
      <Association Name="PHONG_CHITIETHD" Member="PHONG" ThisKey="MAPH" OtherKey="MAPHONG" Type="PHONG" IsForeignKey="true" />
    </Type>
  </Table>
</Database>